### PR TITLE
Sanity Test Fixes

### PR DESCRIPTION
**Pull request by rishabhatdell**
# Description
This PR fixes the outdated sanity tests

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1097 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Ran Sanity Test
image

### CODE REVIEW

**Review by shanmydell — CHANGES_REQUESTED** [review]
Pls update gihub issue id

**Review by shanmydell — APPROVED** [review]

**Comment by adarsh-dell** [comment]
@rishabhatdell The copyright years in all modified files are not correctly updated; please replace 2023 with 2024.

**Comment by rishabhatdell** [comment]
> @rishabhatdell The copyright years in all modified files are not correctly updated; please replace 2023 with 2024.

updated @adarsh-dell

**Review by shanmydell — APPROVED** [review]

**Review by AkshaySainiDell — APPROVED** [review]

**Comment by adarsh-dell** [comment]
> > @rishabhatdell The copyright years in all modified files are not correctly updated; please replace 2023 with 2024.
> 
> updated @adarsh-dell

Thanks @rishabhatdell Approved.

**Review by adarsh-dell — APPROVED** [review]

**Pull request merged**
